"use strict";
exports.__esModule = true;
var index_1 = require("../dist/index");
var arr = ['a', 'b', 'c', 'd', 'e'];
var pieData = (0, index_1.genPieMockData)(arr);
console.log('pie', pieData);
var shuffleData = (0, index_1.shuffleArray)(arr);
console.log('shuffle', shuffleData);
var opNumber = (0, index_1.opDigits)(1.234);
console.log(opNumber);
